version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=demo_database
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - 3307:3306
